Add database
NikitaBatu/java-filmorate pull request #4
Opened 2023-05-20 17:43 UTC by NikitaBatu

2023-05-22 08:08 UTC, GoryachayaG commented
Схема отличная, понятная. 
Единственное, у меня вопрос, **как в этой схеме обеспечивается следующие условие из ТЗ?**

- «дружба» неподтверждённая — когда один пользователь отправил запрос на добавление другого пользователя в друзья,
- «дружба» подтверждённая — когда второй пользователь согласился на добавление.

_Насколько я понимаю, статус friendship из таблицы friends говорит нам, дружат (true) ли эти пользователи или нет(false). 
А если они еще не дружат, но один из них отправил запрос на "дружбу"._ 
**Как это увидеть в этой схеме?**

И было бы здорово добавить описание к схеме, чтобы спустя время самому не заблудиться в ней и тем, кто впервые видит твой код будет проще сориентироваться:)

2023-06-03 12:42 UTC, AnastasiyaFomkina requested changes

2023-06-03 12:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/advice/ErrorHandler.java
> +@RestControllerAdvice(basePackages = "ru.yandex.practicum.filmorate.controller")
basePackages указывать не нужно, спринг корректно найдет нужные компоненты самостоятельно

2023-06-03 12:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/advice/ErrorResponse.java
>      private final String error;
Конструктор и геттер можно обозначить с помощью `lombok`: 
`@Getter`
`@AllArgsConstructor`

2023-06-03 12:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/advice/ErrorHandler.java
> +    public ErrorResponse handleGenreNotFoundException(final ErrorGenreException e) {
Лучше отказаться от именований переменных в одну букву, так код выглядит менее читаемым
```suggestion
    public ErrorResponse handleGenreNotFoundException(final ErrorGenreException exception) {
```

2023-06-03 12:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
[Не рекомендуется](https://habr.com/ru/articles/334636/) внедрять зависимости с помощью field injection, так как оно нарушает принципы [SOLID](https://habr.com/ru/articles/688530/). Лучше заменить на [@RequiredArgsConstructor ](https://www.baeldung.com/spring-injection-lombok#:~:text=Constructor%20Injection%20With%20Lombok) из библиотеки `lombok`. Он автоматически заинжектит все нужные нам поля через конструктор и с его помощью мы избавимся от шаблонного кода

Поправь, пожалуйста, по всему коду

2023-06-03 12:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Friends.java
> +@Data
_Саморазвитие_
Лучше не использовать `@Data`, так как она несет за собой много скрытых проблем. Вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-06-03 12:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Film film : result) {
В коммерческой разработке уже никто давно не пишет обычные циклы, так как они занимают много места и есть stream api для более удобно работы с коллекциями. 

Нужно заменить все циклы в коде на [forEach](https://www.baeldung.com/foreach-java) и стримы

2023-06-03 12:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Film film : films) {
Нужно заменить на [forEach](https://www.baeldung.com/foreach-java)

2023-06-03 17:40 UTC, NikitaBatu commented on src/main/java/ru/yandex/practicum/filmorate/model/Friends.java
> +@Data
Получилось убрать data с трех моделей, на остальных она нужна, т.к. нужны сеттеры, геттеры, хешкод и эквалс. Иначе тесты падают

2023-06-04 12:24 UTC, AnastasiyaFomkina approved these changes

2023-06-04 13:47 UTC, merged